### ISSUE TITLE
pypi release?

### ISSUE THREAD

**Issue by lmjohns3** [dementrock/tensorfuse#2]
I'd love to integrate tensorfuse into a couple of my projects, but I'd be much happier doing so if people could `pip install` tensorfuse as a package dependency (or if I could just list it as a package dependency in my `setup.py` file). Could you upload tensorfuse to pypi at some point? It's fine with me if it's v0.0.1 or something.

**Comment by dementrock** [comment]
Hi @lmjohns3, thanks for your interest! I've registered tensorfuse on pypi: https://pypi.python.org/pypi/tensorfuse/0.0.1. It's far from polished right now and I'm very open for contributions.

**Comment by lmjohns3** [comment]
Awesome, thanks!! I hope to make some contributions this month as I look into it further. Thanks for getting the ball rolling with tensorfuse!
